# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=255, unique=True, verbose_name='Subject identifier')),
                ('userinfo', jsonfield.fields.JSONField(verbose_name='Subject extra data')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OpenID Connect user',
                'verbose_name_plural': 'OpenID Connect users',
            },
        ),
    ]
