# Generated by Django 3.0.8 on 2022-06-02 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_rp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcuser',
            name='iss',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Issuer'),
        ),
        migrations.AlterField(
            model_name='oidcuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='oidcuser',
            constraint=models.UniqueConstraint(fields=('sub', 'iss'), name='unique_sub_in_provider'),
        ),
    ]
